// Generated by gencpp from file kuka_arm/CalculateIK.msg
// DO NOT EDIT!


#ifndef KUKA_ARM_MESSAGE_CALCULATEIK_H
#define KUKA_ARM_MESSAGE_CALCULATEIK_H

#include <ros/service_traits.h>


#include <kuka_arm/CalculateIKRequest.h>
#include <kuka_arm/CalculateIKResponse.h>


namespace kuka_arm
{

struct CalculateIK
{

typedef CalculateIKRequest Request;
typedef CalculateIKResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct CalculateIK
} // namespace kuka_arm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::kuka_arm::CalculateIK > {
  static const char* value()
  {
    return "e2841ca7335735bd34d77773a974ca4b";
  }

  static const char* value(const ::kuka_arm::CalculateIK&) { return value(); }
};

template<>
struct DataType< ::kuka_arm::CalculateIK > {
  static const char* value()
  {
    return "kuka_arm/CalculateIK";
  }

  static const char* value(const ::kuka_arm::CalculateIK&) { return value(); }
};


// service_traits::MD5Sum< ::kuka_arm::CalculateIKRequest> should match 
// service_traits::MD5Sum< ::kuka_arm::CalculateIK > 
template<>
struct MD5Sum< ::kuka_arm::CalculateIKRequest>
{
  static const char* value()
  {
    return MD5Sum< ::kuka_arm::CalculateIK >::value();
  }
  static const char* value(const ::kuka_arm::CalculateIKRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuka_arm::CalculateIKRequest> should match 
// service_traits::DataType< ::kuka_arm::CalculateIK > 
template<>
struct DataType< ::kuka_arm::CalculateIKRequest>
{
  static const char* value()
  {
    return DataType< ::kuka_arm::CalculateIK >::value();
  }
  static const char* value(const ::kuka_arm::CalculateIKRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::kuka_arm::CalculateIKResponse> should match 
// service_traits::MD5Sum< ::kuka_arm::CalculateIK > 
template<>
struct MD5Sum< ::kuka_arm::CalculateIKResponse>
{
  static const char* value()
  {
    return MD5Sum< ::kuka_arm::CalculateIK >::value();
  }
  static const char* value(const ::kuka_arm::CalculateIKResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::kuka_arm::CalculateIKResponse> should match 
// service_traits::DataType< ::kuka_arm::CalculateIK > 
template<>
struct DataType< ::kuka_arm::CalculateIKResponse>
{
  static const char* value()
  {
    return DataType< ::kuka_arm::CalculateIK >::value();
  }
  static const char* value(const ::kuka_arm::CalculateIKResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // KUKA_ARM_MESSAGE_CALCULATEIK_H
